### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ahmed-bashir-ms** [Yadentra/xpath-homework#1]
**This is Feedback, you can close the issue after incorporating the feedback.**

1. **Task 1**
    - ` XPath to select the team member’s name Jane Smith` is incorrect
    -  ` XPath to select the description (which is inside the paragraph) of SEO Services` is incorrect.
    -  `XPath to select all service items in the "Our Services" section` is incorrect.
    -  `XPath to select the email input field in the contact form` is incorrect due to wrong id value.
    -  `XPath to select the entire contact form` is incorrect due to wrong id value.
    -  `XPath to select the first team member's <h4> name` is selecting both team members name. Tweak it to select first team member's name.
    - `XPath to select the "Contact Us" section header (<h2> element)` is incorrect.
    - `XPath to select the first <li> under the "Our Team" section` is incorrect. Wrong element used.
    - `XPath to locate the "Send Message" button in the contact form` is incorrect due to wrong id value.
2. **Task 2: XPath Expressions for Grocerymate**
    - `//button[@class='highlighted-icon']` is incorrect. There is no such element on the page.
    - `//input[@name='username']` is incorrect. The input fields do not have a name attribute. You can inspect the DOM to write a correct XPath. 
    - `//input[@name='password']` is incorrect. Please inspect DOM to write it correctly.
    - `//button[@id='sign-in']` is incorrect.
    - **XPaths for rest of the parts are also incorrect. Please re-do**

**Comment by Yadentra** [comment]
Okay, Will work on it. Thank you
